# 本文件用于配置UI中的文字和图标背景等

label_title:
  type: "QLabel"
  text: "基于YOLOv8v5/LPRNet的车牌检测系统"

label_website:
  type: "QLabel"
  text: "LJC-车牌识别"

label_info:
  type: "QLabel"
  text: "LJC-车牌识别"

label_time_result:
  type: "QLabel"
  text: "0 s"

label_numer_result:
  type: "QLabel"
  text: "0"

label_class_result:
  type: "QLabel"
  text: "None"

label_char:
  type: "QLabel"
  text: "车牌字符"

label_color:
  type: "QLabel"
  text: "车牌颜色"

label_plate_str:
  type: "QLabel"
  text: "省XXXXXX"

label_plate_color:
  type: "QLabel"
  text: "None"

label_score_result:
  type: "QLabel"
  text: "0"

label_xmin_result:
  type: "QLabel"
  text: "0"

label_ymin_result:
  type: "QLabel"
  text: "0"

label_xmax_result:
  type: "QLabel"
  text: "0"

label_ymax_result:
  type: "QLabel"
  text: "0"

textEdit_image:
  type: "QTextEdit"
  text: "选择图片文件"

textEdit_imgFolder:
  type: "QTextEdit"
  text: "选择图片文件夹"

textEdit_video:
  type: "QTextEdit"
  text: "选择视频文件"

textEdit_camera:
  type: "QTextEdit"
  text: "摄像头未开启"

textEdit_model:
  type: "QTextEdit"
  text: "选择模型文件"

MainWindow:
  type: "QMainWindow"
  windowIcon: "icons/icon.png"

centralwidget:
  type: "QWidget"
  background: "icons/#f0f0f0_background.png"

loginTitle:
  type: "QToolButton"
  background: "icons/12.png"

label_bar:
  type: "QLabel"
  background: "icons/weed_logo.png"

Sidebar:
  type: "QWidget"
  background: "icons/blur.png"

toolButton_saveing:
  type: "QToolButton"
  icon: "icons/save.png"

toolButton_menu:
  type: "QToolButton"
  icon: "icons/burger-menu.png"

toolButton_author:
  type: "QToolButton"
  icon: "icons/author.png"

toolButton_version:
  type: "QToolButton"
  icon: "icons/versions.png"

toolButton_file:
  type: "QToolButton"
  icon: "icons/recovery.png"

toolButton_video:
  type: "QToolButton"
  icon: "icons/video.png"

toolButton_camera:
  type: "QToolButton"
  icon: "icons/g1.png"

toolButton_model:
  type: "QToolButton"
  icon: "icons/model.png"

toolButton_folder:
  type: "QToolButton"
  icon: "icons/folder.png"

label_picTime:
  type: "QLabel"
  background: "icons/net_speed.png"

label_picNumber:
  type: "QLabel"
  background: "icons/count.png"

label_picSelect:
  type: "QLabel"
  background: "icons/selection.png"

label_picResult:
  type: "QLabel"
  background: "icons/result.png"

label_picConf:
  type: "QLabel"
  background: "icons/Score.png"

label_picLocation:
  type: "QLabel"
  background: "icons/Ordinateur.png"

label_display:
  type: "QLabel"
  background: "icons/ini-image.png"